[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Christian Ocker <ocker.christian@gmail.com>"]

[dependencies]
char-iter = "0.1"
itertools = "0.7.11"
scan_fmt = "0.1.3"
text_io = "0.1.5"