[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[dependencies]
itertools = "*"
regex = "*"
lazy_static = "*"
text_io = "0.1.7"
ndarray = "0.12.1"
num-traits = "*"
