[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Frank Benkstein <frank@benkstein.net>"]
edition = "2018"

[dependencies]
itertools = "0.7"
regex = "1"
lazy_static = "1.2.0"
chrono = "0.4"